# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08dbe5a23f69a9555d28242e1d78efabb30339b0cd0fd8205ee676dd3648bc4d2fbf96f4106b088992671e12f2d7ace2210ddb5625afb9f6c050173b3a4c7961

test:
  secret_key_base: 4da1b59fdd441450186d92ecf1c7714de512ad8cfdf34b2f8191de20eebd51ac02bac96556b0e4bba9bcae138dbbfa39209803ed1c0e3558b95e6f497de77d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
